(() => {
  const platform = window.miniappI18n || null;
  const platformTranslate = typeof platform?.t === 'function' ? platform.t.bind(platform) : null;
  const platformContext = typeof platform?.getContext === 'function' ? platform.getContext.bind(platform) : null;
  const platformSetLocale = typeof platform?.setLocale === 'function' ? platform.setLocale.bind(platform) : null;

  // GitHub Pages can briefly serve the HTML shell while a locale asset is propagating.
  // Keep the visible Turkish source copy available so dynamic panels never show keys.
  const fallback = {
    app: { eyebrow: 'PİYASA İSTİHBARAT MERKEZİ', title: '08 Analiz', kicker: 'ÇOKLU BORSA TEKNİK TARAMA', heading: 'Pariteyi seç, göstergeleri doğrula.', subtitle: 'Borsayı, para birimini ve zaman dilimini seçin; sistem ortak teknik analiz motoruyla veriyi tarasın.' },
    navigation: { ariaLabel: 'Ana uygulama menüsü', workspace: 'ÇALIŞMA ALANI', overview: 'Genel bakış', scan: 'Tarama ayarları', signals: 'Sinyal panosu', risk: 'Risk ve alarmlar', lab: 'Backtest ve portföy', openMenu: 'Menüyü aç', closeMenu: 'Menüyü kapat', exchangeData: 'BORSA / CANLI DURUM', coreSet: '08 Analiz ortak indikatör seti', gateSet: 'Gate.io uyumlu indikatör seti' },
    actions: { refresh: 'Verileri yenile', scan: 'Seçilen göstergelerle tara', exportCsv: 'CSV indir', exportJson: 'JSON indir', applyPlan: 'Planı risk hesaplayıcıya aktar' },
    status: { live: 'Canlı veri', liveShort: 'Canlı', partial: 'Kısmi canlı veri', unavailable: 'Canlı veri yok', scanning: 'Canlı veri taranıyor...', updated: 'Son tarama', scanningProgress: 'Canlı veri taranıyor: {live} sonuç / {completed} parite kontrol edildi', noLiveData: 'Canlı borsa verisi alınamadı. Sonuç üretilmiyor; bağlantıyı kontrol edip yenileyin.', partialNotice: 'Bazı paritelerden canlı veri alınamadı. Yalnızca doğrulanan canlı sonuçlar gösteriliyor.', catalogNotice: 'Borsa kataloğu canlı olarak alınamadı. Parite listesi gösterilmiyor.', confirmationFailed: 'Çoklu zaman doğrulaması canlı olarak alınamadı.' },
    summary: { ariaLabel: 'Piyasa özeti', tracked: 'Katalogdaki parite', coverage: 'Seçili borsanın spot kataloğu', liveCoverage: 'Canlı analiz: {live} / {total} parite', catalogCount: '{count} spot parite bulundu', buy: 'Al sinyali', buyHint: 'Trend + momentum', buyTimingHint: 'Canlı Al: {approved} · Teknik Al: {technical} · UTC {minute}. dakika referans', sell: 'Sat sinyali', sellHint: 'Zayıflayan yapı', wait: 'Bekle', waitHint: 'Doğrulama bekleniyor', showAll: 'Katalogdaki tüm tarama sonuçlarını göster', showBuy: 'Al sinyallerini göster', showSell: 'Sat sinyallerini göster', showWait: 'Bekle sinyallerini göster' },
    controls: { ariaLabel: 'Tarama ayarları', symbolLabel: 'Parite seç', catalogEmpty: 'Parite seçin', catalogLoading: 'Parite kataloğu hazırlanıyor...', catalogCount: '{count} parite seçilebilir', catalogEyebrow: 'PARİTE KATALOĞU', catalogTitle: 'İşlem yapılacak pariteyi seç', catalogDescription: 'Pariteleri arayarak hızlıca bulabilirsiniz.', catalogClose: 'Katalogu kapat', catalogSearchLabel: 'Parite ara', catalogSearchPlaceholder: 'BTC, ETH veya sembol yazın', catalogQuoteLabel: 'Karşı para birimi', catalogResultsLabel: 'Parite sonuçları', catalogAllQuotes: 'Tüm karşı para birimleri', catalogWatchedOnly: 'Sadece izleme listem', catalogSortLabel: 'Sıralama', catalogSortPopular: 'Hacme göre', catalogSortAz: 'A-Z', catalogResultsEmpty: 'Parite aranıyor...', catalogResults: '{count} parite bulundu', catalogEmptySearch: 'Bu filtrelerle eşleşen parite bulunamadı.', catalogTip: 'Bir parite seçtiğinizde ilgili piyasa taraması başlar.', exchangeLabel: 'Borsa', timeframeLabel: 'Zaman dilimi', indicatorsLabel: '08 Analiz indikatörleri', indicatorsHint: 'Ortak teknik analiz setinde kullanılacak göstergeleri seçin.', indicatorSourceLabel: 'İndikatör seti', indicatorSourceCore: '08 Analiz ortak seti', indicatorSourceGate: 'Gate.io uyumlu seti · 16', indicatorSourceHint: 'Gate.io seti, seçilen canlı OHLCV mumları üzerinde ayrı skorlanır.', gateIndicatorsLabel: 'Gate.io indikatörleri', gateIndicatorsHint: 'Gate.io grafiklerinde bulunan standart gösterge ailesini seçin.', strengthLabel: 'Sinyal gücü', strengthAll: 'Tüm sinyaller', strengthStrong: 'Güçlü sinyaller · ≥70%', confirmationLabel: 'Çoklu zaman doğrulaması', confirmationBadge: '3 TF', confirmationHint: 'Detayda karşılaştırılacak zaman dilimlerini seçin.', searchLabel: 'Sonuçlarda ara', searchPlaceholder: 'Yüklü sonuçlarda ara', volumeFilterLabel: 'Hacim', volumeAll: 'Tüm hacimler', volumeHigh: 'Yüksek · 1,25x+', alignmentLabel: 'TF uyumu', alignmentAll: 'Tüm yapılar', alignmentTwo: 'En az 2 TF', profileLabel: 'Strateji profili', profileBalanced: 'Dengeli', profileScalping: 'Scalping', profileSwing: 'Swing', profileLongterm: 'Uzun vade', qualityLabel: 'Kalite filtresi', qualityAll: 'Tüm kalite sınıfları', qualityAplus: 'Sadece A+', qualityA: 'A ve üzeri', qualityB: 'B ve üzeri', protectionLabel: 'Sinyal koruması', protectionBadge: 'Güvenli mod', protectionHint: 'Açık mum ve düşük kaliteli verileri sonuçlardan ayırın.', confirmedOnly: 'Yalnızca mum kapanışı onaylı', liveQualityOnly: 'Yalnızca güncel canlı veri' },
    timeframe: { '5m': '5 dakika', '15m': '15 dakika', '30m': '30 dakika', '1h': '1 saat', '2h': '2 saat', '4h': '4 saat', '6h': '6 saat', '12h': '12 saat', '1d': '1 gün', '1w': '1 hafta', '1M': 'Aylık' },
    timing: { title: 'Alım zamanlaması', copy: 'Aylık, haftalık, günlük, 4 saatlik, 1 saatlik, 15 dakikalık ve 5 dakikalık analizlerde 06. dakikalar önemlidir; alım kararında UTC dakikasını ayrıca kontrol edin.', timeframesLabel: 'Analiz zaman dilimleri', engineActive: 'Alım zamanlaması izleniyor; sinyal canlı teknik göstergelerden üretiliyor.', monitoring: 'Canlı teknik Al bulundu; UTC 06. dakikası ek teyit referansıdır.', blocked: 'Teknik Al oluştu ancak etkin zamanlama filtresi bekliyor: UTC 06. dakikası dışında Al gösterilmiyor.', approved: 'Teknik Al ve UTC 06. dakikası aynı anda doğrulandı.', disclaimer: 'Bu filtre yalnızca zamanlamayı sınırlar; tek başına yatırım tavsiyesi değildir.' },
    market: { eyebrow: 'TARAMA SONUÇLARI', title: 'Seçili borsanın sinyal panosu', note: 'Emir göndermez', detailHint: 'Detay için satıra tıklayın', pair: 'Parite', price: 'Fiyat', trend: 'Trend', signal: 'Sinyal', score: 'Skor', loading: 'Piyasa verileri yükleniyor...', noResults: 'Bu aramayla eşleşen tarama sonucu yok.', watchlistButton: 'İzleme listem', showAll: 'Tüm taramayı göster', strongOnly: 'Güçlü sinyaller', watchlistOnly: 'İzleme listesi', noWatchlistResults: 'İzleme listenizde bu filtreye uyan parite yok.', filter: { all: 'Tüm tarama sonuçları · {count}', buy: 'Al sinyalleri · {count}', sell: 'Sat sinyalleri · {count}', wait: 'Bekle sinyalleri · {count}' }, noSignalResults: '{signal} sinyali veren parite bulunamadı.' },
    signal: { all: 'Tümü', buy: 'Al', sell: 'Sat', wait: 'Bekle', confidence: 'Güven', quality: 'Kalite' },
    detail: { eyebrow: 'SEÇİLİ PARİTE', provenance: 'Borsa verisi: {exchange} / Analiz motoru: 08 Analiz', provenanceWithProfile: 'Borsa verisi: {exchange} / Analiz motoru: 08 Analiz / Gösterge seti: {profile}', coreIndicatorProfile: '08 Analiz ortak', gateIndicatorProfile: 'Gate.io uyumlu · {count} seçili', provenanceLabel: 'Borsa verisi ve analiz motoru', score: 'Teknik model skoru', ratioNote: 'Al/Sat oranı seçili indikatörlerin uyumudur; sonuç garantisi değildir.', selectedIndicators: 'Seçili indikatör sonuçları', noIndicators: 'Tarama için en az bir indikatör seçin.', confirmationTitle: 'Çoklu zaman dilimi doğrulaması', confirmationLoading: 'Zaman dilimleri karşılaştırılıyor...', confirmationEmpty: 'Karşılaştırılacak zaman dilimi bulunamadı.', confirmationScore: 'Skor', loadingShort: 'Yükleniyor', addWatch: 'İzlemeye ekle', removeWatch: 'İzlemeden çıkar', openExchangeShort: 'Borsada aç ↗', filterEmpty: 'Bu filtrede gösterilecek parite yok.', confidence: 'Teknik güven', trendConfidence: 'Trend', momentumConfidence: 'Momentum', tradePlan: 'İşlem planı taslağı', entry: 'Giriş', stop: 'Stop', takeProfit: 'Hedef', riskReward: 'Risk / getiri', rationaleTitle: 'Sinyal gerekçesi', supporting: 'Destekleyenler', weakening: 'Zayıflatanlar', noFactors: 'Bu koşul için belirgin faktör yok.' },
    history: { title: 'Sinyal geçmişi', lastScans: 'Son taramalar', empty: 'Henüz kayıtlı tarama yok.', changed: 'Değişti', new: 'Yeni', steady: 'Sabit' },
    alerts: { eyebrow: 'ALARM MERKEZİ', title: 'Sinyal değişince haberdar ol', copy: 'İzlediğiniz paritelerde yeni Al, Sat veya sinyal değişimlerini tarama sonrası kaydedin.', enable: 'Alarmları etkinleştir', modeLabel: 'Alarm koşulu', modeChange: 'Sinyal değiştiğinde', modeBuy: 'Yeni Al sinyali', modeSell: 'Yeni Sat sinyali', modeAll: 'Tüm Al / Sat değişimleri', threshold: 'Eşik', watchedOnly: 'Yalnızca izleme listem', liveOnly: 'Yalnızca canlı veri', closedOnly: 'Yalnızca kapanmış mum', recent: 'Son alarmlar', clear: 'Temizle', empty: 'Henüz tetiklenen alarm yok.' },
    risk: { eyebrow: 'RİSK KONTROLÜ', title: 'Pozisyon büyüklüğünü hesapla', copy: 'Bakiyenizin yalnızca belirlediğiniz yüzdesini riske ederek yaklaşık miktarı görün.', balance: 'Bakiye (USDT)', percent: 'İşlem riski (%)', entry: 'Giriş fiyatı', stop: 'Stop fiyatı', fee: 'Komisyon (%)', calculate: 'Hesapla', empty: 'Giriş ve stop fiyatını doldurun.' },
    phase3: { eyebrow: 'STRATEJİ LABORATUVARI', title: 'Backtest ve karşılaştırma', backtestTitle: 'Geçmişte test et', backtestCopy: 'Seçili indikatörleri geçmiş mumlarda deneyin.', run: 'Backtest çalıştır', empty: 'Bir parite seçip backtest çalıştırın.', compareTitle: 'Pariteleri karşılaştır', compareCopy: 'Görünür sonuçları sinyal gücüne göre kıyaslayın.', pair: 'Parite', signal: 'Sinyal', score: 'Skor', volume: 'Hacim' },
    phase4: { eyebrow: 'CANLI TAKİP', title: 'Akış ve manuel portföy', streamConnected: 'Canlı akış bağlı', streamOff: 'Canlı akış kapalı', streamNote: 'Fiyatlar anlık değişebilir; sinyal mum kapanışında doğrulanır.', portfolioTitle: 'Manuel pozisyonlar', side: 'Yön', long: 'Long', short: 'Short', entry: 'Giriş', stop: 'Stop', target: 'Hedef', quantity: 'Miktar', addPosition: 'Pozisyon ekle', noPositions: 'Henüz manuel pozisyon yok.', remove: 'Kaldır' },
    rationale: { buy: 'Trend ve momentum aynı yönde. İşlem öncesi destek, stop ve pozisyon boyutunu ayrıca doğrulayın.', sell: 'Trend zayıf ve momentum negatif. Bu sinyal tek başına pozisyon açma gerekçesi değildir.', wait: 'Göstergeler karışık. Daha net bir yapı veya ek doğrulama beklemek daha sağlıklı olabilir.' },
    indicator: { trend: 'Trend yönü', ema20: 'EMA 20', ema50: 'EMA 50', ema200: 'EMA 200', sma200: 'SMA 200', rsi14: 'RSI 14', macd: 'MACD', shortTrend: 'Kısa trend', longTrend: 'Ana trend', momentum: 'Momentum', direction: 'Yön', bollinger: 'Bollinger', stochastic: 'Stoch RSI', adx: 'ADX', vwap: 'VWAP', volume: 'Hacim oranı', volumeRatio: 'Hacim oranı', volatility: 'Oynaklık', supertrend: 'Supertrend', atr14: 'ATR 14', candleTrend: 'Mum trendi', positive: 'Pozitif', negative: 'Negatif', gateMa20: 'Gate MA 20', gateEma20: 'Gate EMA 20', gateBollinger: 'Gate Bollinger', gateSar: 'Gate SAR', gateRsi: 'Gate RSI 14', gateMacd: 'Gate MACD', gateKdj: 'Gate KDJ', gateCci: 'Gate CCI', gateWr: 'Gate Williams %R', gateAtr: 'Gate ATR 14', gateDmi: 'Gate DMI', gateObv: 'Gate OBV', gateVol: 'Gate VOL', gateRoc: 'Gate ROC', gateMtm: 'Gate MTM', gateStochRsi: 'Gate Stoch RSI' },
    guard: { eyebrow: 'İŞLEM GÜVENLİĞİ', title: 'Sinyal, işlem emri değildir.', copy: 'Bu panel yalnızca analiz üretir. Emir, API anahtarı veya otomatik işlem içermez; her kararı siz doğrularsınız.', pointOne: 'Stop-loss planı', pointTwo: 'Pozisyon boyutu', pointThree: 'Risk/getiri kontrolü' },
    roadmap: { eyebrow: 'GELİŞTİRME PLANI', title: 'Sıradaki yapı taşları', oneTitle: 'Çoklu borsa veri katmanı', oneCopy: 'Ortak sembol ve mum formatı', twoTitle: 'Geniş indikatör motoru', twoCopy: 'Trend, momentum, hacim ve oynaklık', threeTitle: 'Sinyal geçmişi ve backtest', threeCopy: 'Başarı oranı, drawdown ve komisyon', fourTitle: 'Alarm ve bildirim', fourCopy: 'İzlenen parite için koşullu uyarılar', fiveTitle: 'APK paketleme', fiveCopy: 'PWA veya Capacitor Android sürümü' },
    footer: { disclaimer: 'Yatırım tavsiyesi değildir. Sinyalleri kendi stratejiniz ve risk limitlerinizle doğrulayın.', foundation: 'Çoklu borsa temeli' },
    chart: { eyebrow: 'FİYAT HAREKETİ', title: 'Seçili indikatörlerle mum grafiği', candles: 'Mumlar', oscillators: 'Alt göstergeler', loading: 'Seçilen paritenin mum grafiği hazırlanıyor...', empty: 'Bu parite için yeterli mum verisi bulunamadı.', error: 'Grafik şu anda oluşturulamadı. Sayfayı yenileyip tekrar deneyin.', pauseStream: 'Akışı duraklat', resumeStream: 'Akışı sürdür' },
    intelligence: { title: 'Piyasa istihbaratı', regimeLabel: 'Piyasa rejimi', qualityLabel: 'Sinyal kalitesi', volatility: 'Oynaklık', support: 'Yakın destek', resistance: 'Yakın direnç', distance: 'Uzaklık', calibrationEmpty: 'Geçmiş karşılaştırma için henüz yeterli örnek yok.', risk: { low: 'Düşük risk', medium: 'Orta risk', high: 'Yüksek risk' } },
    enhancements: { eyebrow: 'TERMİNAL 2.0', title: 'Komuta merkezi', copy: 'Piyasa genişliği, sinyal sonuçları, portföy riski ve kişisel çalışma alanınız tek görünümde.', heatmapTitle: 'Piyasa ısı haritası', outcomeTitle: 'Sinyal sonuçları', riskTitle: 'Portföy risk radarı', workspaceTitle: 'Çalışma alanım', presetLabel: "Strateji preset'i", applyPreset: 'Uygula', refreshLabel: 'Otomatik tarama', refreshOff: 'Kapalı', notifications: 'Bildirim izni', savePreset: 'Mevcut ayarı kaydet', noteLabel: 'Seçili parite notu', saveNote: 'Notu kaydet', empty: 'Tarama tamamlandığında piyasa özeti burada görünecek.' },
    pro: { eyebrow: 'PROFESYONEL ANALİZ KATMANI', ariaLabel: 'Profesyonel analiz paneli', title: 'Sinyal laboratuvarı', copy: 'Rejim, gerçekleşmiş sonuç, sistem sağlığı ve risk sınırlarını aynı yerde izleyin.', selectedQuality: 'Seçili kalite', regimeTitle: 'Piyasa rejimi', qualityTitle: 'Kalite dağılımı', outcomeTitle: 'Gerçekleşmiş sonuçlar', healthTitle: 'Sistem sağlığı', guardTitle: 'Risk koruma sınırları', noData: 'Veri bekleniyor.' },
    insights: { ariaLabel: 'Sinyal kararlılığı ve kalibrasyonu', eyebrow: 'SİNYAL DAVRANIŞI', title: 'Kararlılık ve kalibrasyon', copy: 'Sinyalin kaç taramada korunduğunu ve geçmiş sonuçlarla düzeltilmiş güveni izleyin.', stability: 'Kararlılık', calibrated: 'Kalibre güven', technical: 'Teknik güven', dataQuality: 'Veri kalitesi', multiTimeframe: 'Çoklu zaman uyumu', conflict: 'Çakışma', aligned: 'Uyumlu', live: 'Canlı', partial: 'Kısmi canlı', unavailable: 'Canlı veri yok' },
    paper: { ariaLabel: 'Sanal işlem terminali', eyebrow: 'SİMÜLASYON MASASI', title: 'Paper trading', copy: 'Gerçek emir göndermeden sinyalleri canlı fiyat, stop ve hedef ile sınayın.', simulation: 'SANAL', balance: 'Sanal bakiye', openPnl: 'Açık K/Z', openTrades: 'Açık işlem', newTrade: 'Yeni sanal işlem', side: 'Yön', long: 'Long', short: 'Short', entry: 'Giriş fiyatı', quantity: 'Miktar', stop: 'Stop fiyatı', target: 'Hedef fiyatı', optional: 'İsteğe bağlı', open: 'Sanal işlemi aç', openList: 'Açık sanal işlemler', closedList: 'Son kapanan işlemler', emptyOpen: 'Henüz açık sanal işlem yok.', emptyClosed: 'Kapanmış sanal işlem yok.', close: 'Kapat', manual: 'Manuel', stopClosed: 'Stop', targetClosed: 'Hedef' },
    auth: { downloadProgress: 'Proje hazırlanıyor: {done}/{total} dosya', downloadSuccess: '{count} dosya ZIP olarak indirildi.', downloadFallback: 'İndirme başlamadıysa ZIP dosyasını buradan indir', downloadError: 'Proje indirilemedi. Tekrar deneyin.', downloadErrorFile: 'İndirme {file} dosyasında takıldı. Yeniden deneyin.' }
  };

  const get = (source, key) => String(key || '').split('.').reduce((value, part) => value && typeof value === 'object' ? value[part] : undefined, source);
  const set = (source, key, value) => { const parts = String(key).split('.'); let target = source; parts.slice(0, -1).forEach((part) => { target[part] ||= {}; target = target[part]; }); target[parts.at(-1)] = value; };
  const replaceValues = (value, values = {}) => String(value).replace(/\{(\w+)\}/g, (_, name) => Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : `{${name}}`);
  const merge = (base, extra) => { const output = { ...base }; Object.entries(extra || {}).forEach(([key, value]) => { output[key] = value && typeof value === 'object' && !Array.isArray(value) ? merge(base?.[key] || {}, value) : value; }); return output; };
  let catalog = fallback;
  const localTranslate = (key, values = {}) => { const value = get(catalog, key); return typeof value === 'string' ? replaceValues(value, values) : String(key); };
  const usableTranslation = (value, key) => typeof value === 'string' && value.trim() && value !== key && !value.startsWith(`${key}.`);
  const translate = (key, values = {}) => { const normalizedKey = String(key || ''); let remote = ''; try { remote = platformTranslate ? platformTranslate(normalizedKey, values) : ''; } catch {} return usableTranslation(remote, normalizedKey) ? remote : localTranslate(normalizedKey, values); };
  const context = () => { try { const value = platformContext?.(); if (value && typeof value === 'object') return value; } catch {} return { resolvedLocale: 'tr', dir: 'ltr', availableLocales: ['tr'], canChangeLocale: false }; };

  window.miniappI18n = { ...(platform || {}), t: translate, getContext: context, setLocale: platformSetLocale || (async () => 'tr') };

  const urls = [new URL('./locales/tr.json', import.meta.url).href, new URL('locales/tr.json', document.baseURI).href].filter((url, index, list) => list.indexOf(url) === index);
  const loadCatalog = async () => {
    for (const url of urls) {
      try {
        const response = await fetch(`${url}${url.includes('?') ? '&' : '?'}v=${Date.now()}`, { cache: 'no-store', credentials: 'same-origin' });
        if (!response.ok) continue;
        const data = await response.json();
        if (get(data, 'app.heading') && get(data, 'market.title')) { catalog = merge(fallback, data); return; }
      } catch {}
    }
    document.querySelectorAll('[data-i18n]').forEach((element) => { const key = element.dataset.i18n; if (key && !get(catalog, key) && element.children.length === 0 && element.textContent.trim()) set(catalog, key, element.textContent.trim()); });
  };
  window.githubI18nReady = loadCatalog();
})();
